name = "propositional_logic"
version = "0.1.0"
keywords = ["math"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "PropositionalLogic"

[[lean_lib]]
name = "PropositionalLogicGrind"

[[lean_exe]]
name = "bench_logic"
root = "Experiment.MainLogic"

[[lean_exe]]
name = "bench_grind"
root = "Experiment.MainGrind"

# lake exe bench_logic
# lake exe bench_grind