name = "propositional_logic"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["propositional_logic"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "PropositionalLogic"

[[lean_exe]]
name = "propositional_logic"
root = "PropositionalLogic.Main"
